magemonkeystudio/fabled

- src/main/java/com/sucy/skill/dynamic/condition/WaterCondition.java
Fix water condition to work with 1.13+ waterlogged blocks.
https://discord.com/channels/818973833570680882/867974987309539368/867975443125526548
> Fix water condition for waterlogged blocks.

- pom.xml
- src/main/java/com/sucy/skill/SkillAPI.java
- src/main/java/com/sucy/skill/api/player/PlayerData.java
- src/main/java/com/sucy/skill/hook/PluginChecker.java
- src/main/java/com/sucy/skill/hook/mimic/MimicHook.java
- src/main/java/com/sucy/skill/hook/mimic/ProSkillApiClassSystem.java
- src/main/java/com/sucy/skill/hook/mimic/ProSkillApiConverter.java
- src/main/java/com/sucy/skill/hook/mimic/ProSkillApiLevelSystem.java
- src/main/resources/plugin.yml
Implementation was ported from Kotlin: https://github.com/EndlessCodeGroup/Mimic/tree/d952ac9/mimic-bukkit/src/main/kotlin/impl/skillapi
Closes #168
> Mimic LevelSystem and ClassSystem hook

- pom.xml
- src/main/java/com/sucy/skill/hook/mimic/MimicHook.java
- src/main/java/com/sucy/skill/hook/mimic/ProSkillApiClassSystem.java
- src/main/java/com/sucy/skill/hook/mimic/ProSkillApiLevelSystem.java
[Mimic 0.7](https://github.com/EndlessCodeGroup/Mimic/releases/tag/v0.7) brings new API for implementations registrations
> Update Mimic integration to 0.7

- src/main/java/com/sucy/skill/SkillAPI.java
- src/main/java/com/sucy/skill/api/player/PlayerData.java
- src/main/java/com/sucy/skill/cmd/CmdRefund.java
- src/main/java/com/sucy/skill/data/Permissions.java
- src/main/java/com/sucy/skill/gui/handlers/AttributeHandler.java
- src/main/java/com/sucy/skill/hook/VaultHook.java
- src/main/java/com/sucy/skill/manager/CmdManager.java
Refund command overhaul & update AttributeHandler.java
> Refund command overhaul & update AttributeHandler.java

- README.md
> Changed form to from

- src/main/java/com/sucy/skill/dynamic/ComponentRegistry.java
- src/main/java/com/sucy/skill/dynamic/trigger/ConsumeTrigger.java
> Add Consume Trigger

- editor/js/component.js
> ProjectileHit and ProjectileTick triggers added to editor

- src/main/java/com/sucy/skill/DataGenerator.java
Potion and Milk bucket are exceptions. It does not count as edible but is still can be consumed.
Remind me if there is a more efficient way to handle these exceptions
> Add Consumable

- src/main/java/com/sucy/skill/dynamic/ComponentRegistry.java
- src/main/java/com/sucy/skill/dynamic/trigger/HealTrigger.java
> Add heal trigger

- src/main/java/com/sucy/skill/api/classes/RPGClass.java
- src/main/java/com/sucy/skill/dynamic/ComponentRegistry.java
- src/main/java/com/sucy/skill/dynamic/mechanic/ExperienceMechanic.java
- src/main/java/com/sucy/skill/listener/ExperienceListener.java
- src/main/java/com/sucy/skill/listener/MechanicListener.java
> ExperienceMechanic implemented

- src/main/java/com/sucy/skill/dynamic/ComponentRegistry.java
- src/main/java/com/sucy/skill/dynamic/mechanic/SkillCastMechanic.java
> Add skill cast mechanic

- src/main/java/com/sucy/skill/listener/ExperienceListener.java
> Permission exp boost

- src/main/java/com/sucy/skill/dynamic/ComponentRegistry.java
- src/main/java/com/sucy/skill/dynamic/condition/TextCondition.java
- src/main/java/com/sucy/skill/dynamic/condition/ValueTextCondition.java
As its name suggests, the condition checks whether the text in the value matches expectations.
VALUE -> Key of the value to be compared
EXPECT -> Strings used for comparison
> add text condition

- src/main/java/com/sucy/skill/api/util/BuffData.java
- src/main/java/com/sucy/skill/listener/BuffListener.java
Fixes bug described in #215 due to armor status not being updated after invisibility effect is being purged by external means
> Invisibility bug fix

- src/main/java/com/sucy/skill/dynamic/trigger/KillTrigger.java
Fixes #446
I don't think there is anything else i can add to this pull request
Though, DeathEvent is not cancellabe in Spigot, so to prevent dying user would have to go for damage and health checks
> Target caster or victim in KillTrigger

- src/main/java/com/sucy/skill/api/player/PlayerData.java
- src/main/java/com/sucy/skill/api/skills/Skill.java
> Attribute skill requirement

- src/main/java/com/sucy/skill/api/util/StatusFlag.java
- src/main/java/com/sucy/skill/dynamic/target/TargetComponent.java
- src/main/java/com/sucy/skill/listener/StatusListener.java
Add new status: Invulnerable
Add new target option: include invulnerable
When entity is in invulnerable, they cant be damage or select by any skill unless the skill described as include invulnerable
> Invulnerable

- src/main/java/studio/magemonkey/fabled/dynamic/mechanic/armorstand/ArmorStandMechanic.java
- src/main/java/studio/magemonkey/fabled/util/ThrowableSupplier.java
> feat: armorstand support for 1.20.1

- src/main/java/studio/magemonkey/fabled/dynamic/ComponentRegistry.java
- src/main/java/studio/magemonkey/fabled/dynamic/mechanic/AbortSkillMechanic.java
- src/main/java/studio/magemonkey/fabled/dynamic/mechanic/DelayMechanic.java
- src/main/java/studio/magemonkey/fabled/dynamic/mechanic/WolfMechanic.java
- src/test/java/studio/magemonkey/fabled/dynamic/mechanic/DelayMechanicTest.java
> update delay mechanic available check

- src/main/java/studio/magemonkey/fabled/dynamic/ComponentRegistry.java
- src/main/java/studio/magemonkey/fabled/dynamic/trigger/JumpTrigger.java
Adds a new trigger that fires whenever a player jumps.
Resolves #335
> [Enhancment] Jump Trigger

- src/api/components/components.svelte.ts
This one actually has the most recent editor changes. :D
> [Enhancement] Action Bar Condition to Editor (Updated)

- package.json
- src/api/blockly/blockly-fields.ts
- src/api/blockly/toolbox-search.ts
- src/components/BlocklyComponentWidget.svelte
- src/components/modal/SettingsModal.svelte
- src/components/sidebar/Sidebar.svelte
- src/data/settings.ts
- src/routes/(app)/[type=istype]/[id]/+page.svelte
Implement `Blockly Mode`, enabling easier and more flexible interactions.
Add settings to toggle `Blockly Mode`.
Note: not thoroughly tested.
You can try it out here: [demo editor](https://dynamiceditor.redirectme.net/)
Just turn on `Blockly Mode` in the setting.
#1018
> Implement Blockly

- src/components/BlocklyComponentWidget.svelte
- src/components/sidebar/SidebarEntry.svelte
- src/data/store.ts
- src/routes/(app)/[type=istype]/[id]/+page.svelte
- src/routes/+layout.svelte
Allow any class/skill/attribute to be associated with a file on the client and automatically save it whenever a change is made.
- Visit my [experiment website](https://dynamiceditor.redirectme.net/)
- Hover into Sidebar entry and click  **sync** button
- Chose which file to link and click **open**
- Click **sync** button again to disconnect
Note: Entry will be green if it is being linked
---
This feature is only available on some browser e.g Edge or Chrome
> New feature "Local Sync"

- pom.xml
- src/main/java/studio/magemonkey/fabled/dynamic/ComponentRegistry.java
- src/main/java/studio/magemonkey/fabled/dynamic/condition/AttackIndicatorCondition.java
sorry for the pom, accidentally added a new line and had to delete it with another commit. I'm new to java so don't be mad
> add attack indicator condition

- src/api/components/components.svelte.ts
This is a follow-up PR for the editor of #1237
> [editor] Ability to append to existing target groups in Remember Target

- src/api/components/components.svelte.ts
Added missing options for HealTrigger in TriggerMechanic
> Options for Heal in TriggerMechanic

- src/api/components/components.svelte.ts
This is a follow-up PR for #1251
> [editor] Fixed DamageBuffMechanic & DefenseBuffMechanic for skills

- src/api/components/components.svelte.ts
> [editor] Refactor SkillCastMechanic to support non-player targets

- src/main/java/studio/magemonkey/fabled/cmd/CmdSkill.java
> Adding in group skill command

- src/main/java/studio/magemonkey/fabled/dynamic/ComponentRegistry.java
- src/main/java/studio/magemonkey/fabled/dynamic/trigger/StripLogTrigger.java
New trigger for when a player strips a log.
> [Enhancement] Strip Log Trigger

- src/main/java/studio/magemonkey/fabled/dynamic/ComponentRegistry.java
- src/main/java/studio/magemonkey/fabled/dynamic/trigger/FlagExpireTrigger.java
- src/main/java/studio/magemonkey/fabled/dynamic/trigger/FlagTrigger.java
Adds two new Triggers Flag and FlagExpires
- Flag : Activates when the specified flags are given to a player.
- FlagExpires : Activates when the specified flags expire on a player.
> Flag Triggers
